create table if not exists public.patients (
    id bigint generated by default as identity primary key,
    name text not null default 'Unknown',
    health_id text not null default 'N/A',
    lang text not null default 'en',
    age_group text not null default 'Adult',
    answers jsonb not null default '{}'::jsonb,
    ai_priority integer not null default 1,
    nurse_priority integer null,
    ai_reason text null,
    status text not null default 'pending_nurse',
    "timestamp" timestamptz not null default timezone('utc', now()),
    nurse_verified_at timestamptz null,
    called_at timestamptz null
);

create index if not exists patients_status_idx on public.patients (status);
create index if not exists patients_priority_idx on public.patients (ai_priority desc, "timestamp" asc);

create table if not exists public.age_scans (
    id uuid primary key,
    age_bucket text null,
    age_group text null,
    confidence double precision null,
    next_step text null,
    device_name text not null default 'raspberry-pi',
    session_id text null,
    created_at timestamptz not null default timezone('utc', now())
);

create index if not exists age_scans_created_at_idx on public.age_scans (created_at desc);
